line-length = 132
indent-width = 2

[format]
quote-style = "double"            # Like Black, use double quotes for strings.
skip-magic-trailing-comma = false # Like Black, respect magic trailing commas.
indent-style = "space"            # Like Black, indent with spaces, rather than tabs.
line-ending = "auto"              # Like Black, automatically detect the appropriate line ending.

exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "site-packages",
  "venv",
]
